apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: blue3
spec:
  config: '{
    "cniVersion":"0.4.0",
    "name": "blue3-net",
    "plugins": [
      {
        "type": "jcnr",
        "args": {
          "vrfName": "blue3",
          "vrfTarget": "65000:300"
        },
        "kubeConfig":"/var/lib/kubelet/kubeconfig"
      }
    ]
  }'

---

apiVersion: v1
kind: Pod
metadata:
  name: podblue3
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "blue3",
          "interface":"eth1",
          "cni-args": {
            "interfaceType":"veth",
            "dataplane":"dpdk",
            "mac":"aa:bb:cc:dd:ee:33",
            "ipConfig":{
              "ipv4":{
                "address":"12.1.0.10/24",
                "gateway":"12.1.0.1",
                "routes":["11.1.0.0/24"]
              }
            }
          }
        }
      ]
spec:
  containers:
    - name: podblue3
      # image: public.ecr.aws/ubuntu/ubuntu:22.04
      # image: public.ecr.aws/docker/library/busybox:1.36
      image: public.ecr.aws/docker/library/alpine:latest
      command: ["sleep", "604800"]
      ports:
        - containerPort: 80
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_NICE
            - SYSLOG
            - SYS_PTRACE
            - SYS_RAWIO

