name: TOC Generator

on:
  push:
    paths:
      - 'README.md'

jobs:
  generateTOC:
    name: Generate TOC
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate TOC
        uses: technote-space/toc-generator@v4
